### ISSUE TITLE
how to use StartActivityForResult 

### ISSUE THREAD

**Issue by tuhin10** [takahirom/PreLollipopTransition#12]
I have couple of questions
1. How can I use StartActivityForResult and get the status and return intent in onActivityResult ?
2. How to pass data via intent and get the data back in the opened Activity ?

**Comment by takahirom** [comment]
1. Now, you can't use startActivityForResult. I will add it next release! 
   Thank you for feedback :)
2. You can like this

Put extra

``` java
                final Intent intent = new Intent(MainActivity.this, SubActivity.class);
                intent.putExtra("extra", "test");
                ActivityTransitionLauncher
                        .with(MainActivity.this)
                        .from(v)
                        .launch(intent);
```

Get data in the opened Activity

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sub);
        Toast.makeText(this, getIntent().getStringExtra("extra"), Toast.LENGTH_SHORT).show();
        exitTransition = ActivityTransition.with(getIntent()).to(findViewById(R.id.sub_imageView)).start(savedInstanceState);
    }
```

**Comment by tuhin10** [comment]
@takahirom thanx for your reply............ will wait for release.

**Comment by ossamaweb** [comment]
@takahirom  Hi, awesome lib! When start activity methods gonna be available? Thanks ;)

**Comment by takahirom** [comment]
@ossamaweb 
Thanks!
I will do that today or tomorrow.

**Comment by ossamaweb** [comment]
@takahirom Awesome! Looking forward for it. Thanks!

**Comment by takahirom** [comment]
@tuhin10 @ossamaweb 
You can use that in 1.2.0 !
Like this.
https://github.com/takahirom/PreLollipopTransition/commit/4ed54ddd7e1273cd8c25420593533adb3929d6de
