### ISSUE TITLE
use in Adapter

### ISSUE THREAD

**Issue by tellfa** [takahirom/PreLollipopTransition#15]
how to use this library in Adapter?
for example my adapter is : 
    public DataAdapter(List<newSMS_class> sms_list_use, RecyclerView recyclerView, Context context) {
.
.
.
                public void onClick(View view) {
                    final Dialog nagDialog = new Dialog(view.getContext());
                    nagDialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
                    nagDialog.setContentView(R.layout.dialog_iamge);
                    ImageView ivPreview = (ImageView) nagDialog.findViewById(R.id.dialog_image);
                    int loader = R.drawable.all_users_avatar;
                    Picasso.with(view.getContext())
                            .load(Address_class.server_ip() + "UploadUserImage/Avatar/img_" +
                                    sms_username.getTag() + ".jpg")
                            .error(loader)
                            .into(ivPreview);
                    ActivityTransitionLauncher.with((Main_Page)mcontext).from(view).launch(nagDialog);
                    nagDialog.show();
}

tnx

**Comment by takahirom** [comment]
Sorry, currently not support Dialog.
Please consider using themed activity.
http://stackoverflow.com/a/1979631

**Comment by tellfa** [comment]
tnx, Is this the correct way for adapter?
my mean is : ActivityTransitionLauncher.with((Main_Page)mcontext).from(view).launch(nagDialog);

**Comment by tellfa** [comment]
please help me to use this in Adapter

**Comment by takahirom** [comment]
Sorry for late.
launch() argument type is Intent . And your argument type is Dialog. So,Probably it is wrong.

**Comment by tellfa** [comment]
I do not want use Dialog. i want open Activity but start in Adapter!
how to use (use this library for open Activity) in Adapter? 
please send me current code. tnx <3
i need this library

**Comment by takahirom** [comment]
Prease use like this.

``` java
final Intent intent = new Intent((Main_Page)mcontext, GoToActivity.class); 
ActivityTransitionLauncher.with((Main_Page)mcontext).from(view).launch(intent);
```

**Comment by tellfa** [comment]
tnx, use this but this class (GoToActivity) does not know. 
how tu edit this?
can you send to me complete code? tnx

**Comment by tellfa** [comment]
Use this code, but when start show mw FC Error : 
LogCat error : 10-17 09:51:56.184  13259-13259/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.tellfa.smsbox, PID: 13259
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
            at android.content.ComponentName.<init>(ComponentName.java:77)
            at android.content.Intent.<init>(Intent.java:4010)
            at com.tellfa.smsbox.adapters.DataAdapter$StudentViewHolder$2.onClick(DataAdapter.java:236)
            at android.view.View.performClick(View.java:4764)
            at android.view.View$PerformClick.run(View.java:19844)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5349)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by takahirom** [comment]
Your mcontext variable is maybe null.

**Comment by tellfa** [comment]
my code is : 
public class DataAdapter extends RecyclerView.Adapter { 
...
    private Context context;
}

public DataAdapter(List<newSMS_class> sms_list_use, RecyclerView recyclerView, Context mContext) {

```
    this.context = mContext;
```

...
}

can you help me too fix it? tnx

**Comment by takahirom** [comment]
Please add this

``` java
Log.d("context","context:"+mcontext);
```

or 
Please use `view.getContext()`.

**Comment by tellfa** [comment]
tnx, where in use this code? view.getContext().
can you send me completely code? tnx

**Comment by takahirom** [comment]
``` java
final Intent intent = new Intent((Main_Page)view.getContext(), GoToActivity.class); 
ActivityTransitionLauncher.with((Main_Page)view.getContext()).from(view).launch(intent);
```

**Comment by tellfa** [comment]
tnx, iiiiiiiiiiiiiiiiiiiiiiiits oooooooookey
you are amazing maaaaaaaaaaan <3

**Comment by takahirom** [comment]
:+1:
