### ISSUE TITLE
Show Animations

### ISSUE THREAD

**Issue by tellfa** [takahirom/PreLollipopTransition#16]
Hi. thanks you for Previous help. i have one question.
i want start animation such as this picture : 
![](https://cloud.githubusercontent.com/assets/1386930/7614211/53ca12d8-f9d0-11e4-8b98-b6d98272f67d.gif)

set imageview Top of activity, and after the set this image. sort under this image another objects.
How can I do this? please send me correct code. 
tnx <3

**Comment by takahirom** [comment]
You can like this. In onCreate().

``` java
detailsContainer.setTranslationY(1000); // you can use screen height
detailsContainer.animate().translationY(0).setDuration(300)
                .setStartDelay(400);
```

**Comment by tellfa** [comment]
tnx, i'm Amateur. can you send me full code?

**Comment by takahirom** [comment]
Please look this.
https://github.com/takahirom/WearLocationWatchFace/blob/master/app/src/main/java/com/kogitune/wearlocationwatchface/activity/PhotoDetailActivity.java

**Comment by tellfa** [comment]
i love you maaaaaaaaaaan. tnx <3

**Comment by takahirom** [comment]
:ok_hand:
