### ISSUE TITLE
reverse animation

### ISSUE THREAD

**Issue by ghost** [takahirom/PreLollipopTransition#2]
what about reverse animation on activity back pressed?  for example i have small image clicking on image opens a new activity with full size image and on back pressed that image will scale down to same size image on previous activity.

**Comment by takahirom** [comment]
@dhrumit123 
Thank you for suggestions.
I've implemented it.

You can do like this.

```
    private ExitActivityTransition exitTransition;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sub2);
        exitTransition = ActivityTransition.with(getIntent()).to(findViewById(R.id.sub_imageView)).start(savedInstanceState);
    }
    @Override
    public void onBackPressed() {
        exitTransition.exit(this);
    }
```
