### ISSUE TITLE
At the beginning, the image be scaled.

### ISSUE THREAD

**Issue by NtcWai** [takahirom/PreLollipopTransition#27]
Thank you for the useful library. 
I have 2 images with different ratio. In the start activity:
![2016-03-07 18 34 51](https://cloud.githubusercontent.com/assets/1621221/13565542/05ea46f0-e494-11e5-8f1b-d8659906f326.png)
In the destination activity, at the end, it like that:
![2016-03-07 18 36 05](https://cloud.githubusercontent.com/assets/1621221/13565574/33160862-e494-11e5-84a1-69d1662bab89.png)
But  at the beginning, it be scaled:
![2016-03-07 18 38 30](https://cloud.githubusercontent.com/assets/1621221/13565561/2158fdf0-e494-11e5-9f24-5eabe5e277da.png)
On API >=21 it's fine.
How to make the image don't be scaled.
Thank you very much.

**Comment by takahirom** [comment]
Thank you for reporting!
Where is the branch you are running the sample?
If you try in develop branch, Please try master branch.

**Comment by NtcWai** [comment]
Thank you for quickly response.
I have switched to master branch, but nothing changed.

**Comment by takahirom** [comment]
OK! 
I'll try to look.
But, I'm sorry, I am currently a little busy.
I'll try to look into the weekend.

**Comment by takahirom** [comment]
I am sorry for the late response. 
Sorry, If you a different image in the start Activity and destination Activity, Currently This library not supported.
