### ISSUE TITLE
Crashes on 4.0.4 (API 15)

### ISSUE THREAD

**Issue by kolorszczak** [takahirom/PreLollipopTransition#28]
Each transition in API15 (Android 4.0.4) ends up crashing because inside your library you load support-v4 with "+" at the end, meaning that you load it from the alpha channel

**Comment by takahirom** [comment]
Thank you for reporting! And sorry.
I will fix that next release.

You can use this workaround.

``` java
    compile('com.kogitune:pre-lollipop-activity-transition:1.3.0') {
        exclude module: 'support-v4'
    }
```
