### ISSUE TITLE
Why using file to transfer Bitmap?

### ISSUE THREAD

**Issue by dkmeteor** [takahirom/PreLollipopTransition#3]
Bitmap implements Parcelable.
Can just put it in Intent bundle?

**Comment by dkmeteor** [comment]
I/O is expensive and slow.

**Comment by takahirom** [comment]
Thank you for suggestion. 
I want to fix too.
I had been trying in a way to pass a bitmap with Intent. but, It cause TransactionTooLargeException.  http://stackoverflow.com/questions/19066589/transactiontoolargeexception-when-sending-large-data-through-intent-extras

**Comment by shiraji** [comment]
Does this saveImage process always required? I think this is a backup plan when there is [no bitmap memory in the static field](https://github.com/takahirom/PreLollipopTransition/blob/fbf7dcb2289375f73d29b99aeea53de206e0ca31/pre-lollipop-activity-transition/src/main/java/com/kogitune/activity_transition/core/TransitionAnimation.java#L75-L77).

If this is true, then this library should make this process background and then create image if there is no bitmap in static field and after the background process is completed.

What do you think @takahirom ?

**Comment by takahirom** [comment]
@shiraji 
I think it is good!
I added you to collaborator :)
I will look your implementation!

**Comment by shiraji** [comment]
Thanks! This is the first time someone added me as a contributor in his/her README!

**Comment by shiraji** [comment]
So now, I reopen this issue.

**Comment by takahirom** [comment]
Fixed
