### ISSUE TITLE
Excuse me, how I have no in the example in the project ？

### ISSUE THREAD

**Issue by i91h1r** [takahirom/PreLollipopTransition#37]
this is Activity A:( in adpter)
  imageView.setOnClickListener(new View.OnClickListener() {
                                @Override public void onClick(View v) {

```
                                final Intent intent = new Intent(AllCopyRightActivity.this, ApplyProcessActivity.class);
                                ActivityTransitionLauncher.with(AllCopyRightActivity.this).from(v.findViewById(R.id.iv)).launch(intent);
                            }
                        });
```

this is Activity B :
    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ActivityTransition.with(getIntent()).to(imageView).start(savedInstanceState);
    }

**Comment by takahirom** [comment]
I can't understand.
What's the problem?
