### ISSUE TITLE
Fragment transitions?

### ISSUE THREAD

**Issue by allonmj** [takahirom/PreLollipopTransition#4]
Is it possible to support fragment transitions too?

**Comment by takahirom** [comment]
Probably , Yes.
I will try.

**Comment by xiaomeixw** [comment]
should support activity to activity , support activity to fragment,support fragment to activity ,support fragment to fragment , support inflater view to activity, support inflater view to fragment, support inflater view to Inflater view .....Thanks....

**Comment by takahirom** [comment]
@allonmj 
Thank you for suggestion.
Support fragment transition in version 1.0.0.
