### ISSUE TITLE
can't add listeners

### ISSUE THREAD

**Issue by stavkidron** [takahirom/PreLollipopTransition#43]
I'm trying to implement your code in my app and I see in your SubActivity you added listeners to the exitTransition. When I tried to do it, it marked it as red and I couldn't add the listener myself. My imports are the same as yours, am I missing something? Do I need another library? 

here's the code example: 

```
exitTransition.exitListener(new AnimatorListenerAdapter() {
          
            public void onAnimationStart(Animator animation) {
                Log.d("TAG", "onOutAnimationStart!!");
            }
            public void onAnimationEnd(Animator animation) {
                Log.d("TAG", "onOutAnimationEnd!!");
            }
        });

```
.exitListener is shown as an error. When I open your project it looks fine. Also same thing with .enterListener.

**Comment by takahirom** [comment]
Sorry currently version(1.3.2) does not contain listener.
I released Version 1.3.3 now and this version contains listener. Can you try it?
