### ISSUE TITLE
App crashes on pre-Lollipop

### ISSUE THREAD

**Issue by ClaudeHangui** [takahirom/PreLollipopTransition#45]
I ran the app on a samsung device (kitkat)  and the app crashed. 
I cloned the project and launched it on kitkat device the app crashed. I created a new project, went the other way round i.e I added the library in the gradle file I still got the same crash .. Beyond api 19 it seems to work. I tested using the sample and by creating a custom project (and hence importing the library in the gradle file) it works perfectly .....

The error is on the MainActivity:         
this is the line where the error points to: super.onCreate(savedInstanceState);

Exception while inflating <vector>org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportHeight > 0

Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052

Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector

**Comment by takahirom** [comment]
The cause of the crash is obviously VectorDrawable.
This library is irrelevant.

FYR
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.t5ojhmpum

**Comment by ClaudeHangui** [comment]
Yeah....I just saw that: 
However as per the [official documentation from google](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html)
all you need to do (i.e if you want to support vector drawables for pre-lolipop) is to add
vectorDrawables.useSupportLibrary = true
to in your gradle file 
Moreover you need to use the new app:srcCompat attribute. So, instead of using:

`<ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@drawable/triangle"/>`

you should use

`<ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:srcCompat="@drawable/triangle"/>`

I applied the changes and it now works on my kitkat device

**Comment by takahirom** [comment]
I don't know that documentation!
Thanks

**Comment by ClaudeHangui** [comment]
So one more thing: How will I go about to transition text together with images ???

i.e if I have a list of items where each item has an image (on the left) and some text (on the right).
 
A click on an item should provide a transition for both the image and the text: i.e on opening a new fragment which provides the details for that item, the image moves up (as per the demo), meanwhile the text moves down i.e below the image.
Can the library solve this problem ???

**Comment by takahirom** [comment]
Can you upload screen shot?

**Comment by ClaudeHangui** [comment]
Hi, I think [this link](https://android-arsenal.com/details/3/4114) speaks more than a plain, still screenshot :)...

Of course the textview doesn't have a "perfect animation" but the idea (at least from my perspective) is to see it popping out from the bottom...

you can check out the [AndroidAuthority app](https://play.google.com/store/apps/details?id=com.androidauthority.app&hl=en) which gives a perfect illustration of what i'm talking about

**Comment by ClaudeHangui** [comment]
Simply put: how do I accomplish what we see (the transition/animation effect) on the gif file you provided as an illustration of how the library works ?

**Comment by takahirom** [comment]
You can do that following code

```
view.setTraslateY(2000);// screen height
view.animate().translationY(0);
```

**Comment by ClaudeHangui** [comment]
thanks....but where exactly do I add these lines of code ??
Moreover from your ActivityTransitionLauncher and FragmentTransitionLauncher classes how do I include the textview  when I call from(View fromView) method in my code ??

**Comment by takahirom** [comment]
Full code is here
https://github.com/takahirom/WearLocationWatchFace/blob/b994e3cfd536886687a496ff21265caaafc973c2/app/src/main/java/com/kogitune/wearlocationwatchface/activity/PhotoDetailActivity.java#L186

I forgot that probably you should use OnPreDrawListener in detail activity.
