### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by d3bt3ch** [takahirom/PreLollipopTransition#50]
App crashes when I include,

compile 'com.kogitune:pre-lollipop-activity-transition:1.3.3'

with error ...

Binary XML file line 15: Error inflating class com.ihsanbal.wiv.MediaView

**Comment by takahirom** [comment]
Probably It is occurred by Support Library version up.

Probably, You can use this workaround.

    compile('com.kogitune:pre-lollipop-activity-transition:$version') {
        exclude module: 'support-v4'
    }
