### ISSUE TITLE
How to use this library for starting transition from listview row?

### ISSUE THREAD

**Issue by bahacan19** [takahirom/PreLollipopTransition#6]
I want to use this to start from listview row.
thnx

**Comment by takahirom** [comment]
Sorry for my poor English.

Do you want to run the animation when you click an item in the ListView?
Do you have ImageView you want to animate in the Item of ListView?

**Comment by bahacan19** [comment]
I want to run the animation when I click an item in the ListView.

**Comment by derekcsm** [comment]
@bahacan19 you need a reference to the view in your list item, then it'll work.

Edit: Actually yeah I'm having this issue too, the image will scale it's size properly but not translate from it's coordinates in the ListView

**Comment by takahirom** [comment]
@bahacan19 @derekcsm 
I am sorry that my reply to you is delayed.
I added ListView to example app.
I hope this will help.
https://github.com/takahirom/PreLollipopTransition/blob/master/sample-app/src/main/java/com/kogitune/prelollipoptransition/ListViewActivity.java
