### ISSUE TITLE
Image be cut by ViewGroup

### ISSUE THREAD

**Issue by icyfox-bupt** [takahirom/PreLollipopTransition#7]
Firstly thanks to this, it is good and I have run several tests and they all works good.

But when a **view** is in a **ViewGroup** and if the ViewGroup not full screen , then when the transition move to  a position that the ViewGroup not covered, the view will disapper, can we fix this problem?

**Comment by takahirom** [comment]
Thank you for reporting.
I tested it and it occurred.
I found this question. I added `android:clipChildren="false"` for parent layout.
http://stackoverflow.com/a/24564277

It maybe fixed  :)
Please confirm it.
https://github.com/takahirom/PreLollipopTransition/blob/master/sample-app/src/main/res/layout/activity_sub2.xml#L5

**Comment by icyfox-bupt** [comment]
thank you and

when update it at **Gradle** ? thx.

**Comment by takahirom** [comment]
You can fix by changing your app layout :)
Please add layout `android:clipChildren="false"` attribute to your container layout.

This is sample code.
https://github.com/takahirom/PreLollipopTransition/blob/master/sample-app/src/main/res/layout/activity_sub2.xml#L5
