### ISSUE TITLE
getArguments().getParcelable doesn't work with FragmentTransitionLauncher

### ISSUE THREAD

**Issue by TheLester** [takahirom/PreLollipopTransition#8]
I am using FragmentTransitionLauncher with shared resource(image) from one fragment to another:

```
  final MoreAppInfoFragment toFragment = MoreAppInfoFragment.newInstance();
  FragmentTransitionLauncher.with(getActivity()).image(myBtimap).
  from(iconHolder).prepare(toFragment);
```

I noticed that FragmentTransitionLauncher.prepare() method creates new Bundle obj sets him to fragment:

```
   public void prepare(android.support.v4.app.Fragment toFragment) {
   Bundle transitionBundle = TransitionBundleFactory.createTransitionBundle(this.context,
   this.fromView, this.bitmap);
   toFragment.setArguments(transitionBundle);}
```

So instead of creating new Bundle, i get existing and put my Parcelable like this:

```
    toFragment.getArguments().putParcelable(MoreAppInfoFragment.APP_INFO_OBJ,    
    Parcels.wrap(new AppInfo()));
```

And then start my fragment:

```
     getFragmentManager().beginTransaction().replace(R.id.fragmentContainer, 
     toFragment).addToBackStack(null).commit();
```

And finally in my MoreAppInfoFragment onViewCreated i getArguments and it returns null:

```
    public void onViewCreated(View view, Bundle savedInstanceState) {
    AppInfo currentApp = 
    Parcels.unwrap(getArguments().getParcelable(APP_INFO_OBJ));//getArguments() = null}
```

**Comment by takahirom** [comment]
Thank you for reporting.
I tried it , but not reproduce. Please tell me how to reproduce.
https://github.com/takahirom/PreLollipopTransition/commit/40a043d4c579b5382e0eb1745ddb36c7e232675a

**Comment by TheLester** [comment]
@takahirom  Never mind,It was my bug, but anyway it would be good to mention in documentation that developer can't create new Bundle object and should use existing by getArguments()

**Comment by takahirom** [comment]
@TheLester 
Thank you for feed back.
I will add that to README.
