### ISSUE TITLE
Interpolator

### ISSUE THREAD

**Issue by FunnyDevs** [takahirom/PreLollipopTransition#9]
Hi and congratulations for the library! Is possibile to have an option to change interpolator???  Thanks

**Comment by takahirom** [comment]
Thank you for comment.
Now you can't do that. 
I will add that option next release!

**Comment by takahirom** [comment]
Hi!
1.1.0 released. It contains Interpolator support. 
https://github.com/takahirom/PreLollipopTransition/releases/tag/1.1.0

**Comment by kainjinez** [comment]
Can you explain a bit how to use with interpolator? Thanks
